import { Geist, Geist_Mono } from "next/font/google";
import {Metadata} from "next";

// import "./globals.css";
// import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: "Product",
    template: "%s | Product Title"
  },
  description: "Generated by create next app",
};

export default function ProductLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <header className="bg-orange-600 py-2">
          <p className="text-center">Header</p>
        </header> */}
        {children}
        <footer className="bg-green-600 py-2">
          <p className="text-center">Footer</p>
        </footer>
      </body>
    </html>
  );
}
